In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr1 = np.array([[1,2,3],[5,6,7]])

print(arr1)
print(arr1[1,1])
print(arr1[0,1] + arr1[1,2])


[[1 2 3]
 [5 6 7]]
6
9


In [ ]:
arr2 = np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[1,3,5,7,9],[2,4,6,8,0]]])
arr2


array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]],

       [[1, 3, 5, 7, 9],
        [2, 4, 6, 8, 0]]])

In [ ]:
print(arr2.shape)

(2, 2, 5)


In [ ]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])

arr5 = np.concatenate((arr3,arr4))
arr5

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr6 = np.array([[1,3,6],[2,4,8]])

arr7 = np.concatenate((arr1, arr6), axis= 1)

for i in arr7:
  print(i)

[1 2 3 1 3 6]
[5 6 7 2 4 8]


In [ ]:
arr7 = np.hstack((arr1, arr6))
arr7

array([[1, 2, 3, 1, 3, 6],
       [5, 6, 7, 2, 4, 8]])

In [ ]:
spltarr = np.array_split(arr5, 3)
spltarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
x = np.where(arr2 == 4)
x


(array([0, 1]), array([0, 1]), array([3, 1]))

In [ ]:
y = np.sort(arr2)
y

array([[[1, 2, 3, 4, 5],
        [0, 6, 7, 8, 9]],

       [[1, 3, 5, 7, 9],
        [0, 2, 4, 6, 8]]])

In [ ]:
fruits = np.array(['Banana', 'Apple', 'Mango', 'Pineapple', 'Strawberry', 'Blackberry'])
z = np.sort(fruits)
z

array(['Apple', 'Banana', 'Blackberry', 'Mango', 'Pineapple',
       'Strawberry'], dtype='<U10')

In [ ]:
from numpy import random

a = random.randint(100)
a


60

In [ ]:
b = random.rand()
b

0.3667826688662953

In [ ]:
c = random.randint(100, size=(10))
c

array([45, 73, 67,  4, 65, 19, 61, 19, 61, 39])

In [ ]:
d = random.rand(5)
d

array([0.67712354, 0.45687204, 0.46911866, 0.17464186, 0.50146835])

In [ ]:
r = random.choice([1,2,3,4,5,6,7,8,9,0], size=(5,5))
r

array([[9, 1, 5, 0, 1],
       [4, 9, 1, 0, 3],
       [3, 8, 2, 6, 7],
       [7, 9, 2, 8, 6],
       [8, 5, 3, 7, 7]])

In [ ]:
rd = random.choice([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], size = (4,3,5))
rd

array([[[18,  1, 16, 10, 10],
        [10,  8,  9,  2, 20],
        [11, 18,  8, 17, 17]],

       [[ 2,  9, 19,  1,  3],
        [16,  8, 17, 13, 11],
        [16, 13, 11, 17,  2]],

       [[20,  6, 13, 18, 17],
        [17,  4,  1,  8,  2],
        [20,  8, 10,  5,  6]],

       [[ 2, 20,  8,  8, 10],
        [ 8,  9,  8,  1,  7],
        [13,  5,  3, 20,  6]]])

In [ ]:
rdarr = random.choice([1,3,5,7,9], p = [0.1,0.3,0.2,0.4,0.0], size = (2,50))
rdarr

array([[7, 5, 3, 1, 3, 3, 5, 3, 3, 1, 7, 7, 3, 3, 3, 3, 3, 3, 7, 7, 3, 1,
        7, 7, 3, 7, 5, 7, 5, 7, 5, 7, 7, 7, 1, 5, 3, 3, 1, 7, 3, 5, 3, 7,
        3, 5, 7, 5, 3, 3],
       [7, 5, 7, 3, 7, 7, 5, 5, 7, 3, 7, 3, 7, 7, 7, 3, 7, 3, 5, 1, 3, 3,
        7, 7, 7, 5, 7, 7, 5, 3, 3, 1, 5, 7, 3, 1, 7, 5, 3, 5, 1, 3, 7, 3,
        3, 3, 5, 7, 7, 7]])

In [ ]:
ar = np.array([1,2,3,4,5,6])
random.shuffle(ar)
print(ar)

[2 3 1 6 5 4]


In [ ]:
print(random.permutation(ar))

[2 6 1 4 3 5]


In [ ]:
[:
 tempansx:  == stringname]